### PR TITLE
Refactor Plug.vala

### PR DESCRIPTION
**Pull request by donadigo**
* Remove unneded and not working `connected` signal
* Use `unowned` for unowned variables
* Put more complex lambdas into their own callbacks
* Cache some variables for later use

### CODE REVIEW

**Comment by jeremypw** [comment]
There appears to be a regression in that "Complete Installation" has no effect in this PR whereas in master installation starts.

**Comment by donadigo** [comment]
@jeremypw I can't reproduce that on master, it's the same there as in my branch unless I do something wrong...

**Comment by jeremypw** [comment]
OK, I'll look into it further.  I testing on Juno.

**Comment by jeremypw** [comment]
@donadigo :  Do you mean that in both your PR and master, the incomplete installation is restarted?  For me with your PR, the warning bar disappears after clicking on "Complete installation" but no progress bar appears (whether or not I authenticate first).

**Comment by jeremypw** [comment]
Needless to say, I install the plug before testing.

**Comment by jeremypw** [comment]
It seems there is an error in UbuntuInstaller.  In `public async void check_missing_languages ()`, there should not be `var` in front of `missing_languages`.  Removing this fixes the problem for me.  This error is in the current master so I must have had an older version installed.

**Comment by jeremypw** [comment]
Looks like 676d857c987065137bfefc13a2f744adcd07c6ec is responsible.

**Comment by jeremypw** [comment]
Just pushed PR fixing this.

**Pull request merged**
