### PR TITLE
LocaleSetting: Region ComboBox → DropDown

### PR DESCRIPTION
**Pull request by danirabbit**

### CODE REVIEW

**Review by jeremypw — CHANGES_REQUESTED** [review]
The region is not initialised to the current region

**Comment by danirabbit** [comment]
@jeremypw my bad that was totally fucky. It should be fixed now

**Comment by jeremypw** [comment]
Nearer, but its still initialising to "United States" instead of "United Kingdom" for me.

**Comment by jeremypw** [comment]
The problem is that the selected locale is changed to a less close match *after* it has already been set to the user locale.

**Comment by danirabbit** [comment]
@jeremypw ah I understand the issue now :sweat_smile: Will fix

**Comment by danirabbit** [comment]
@jeremypw okay, should really be fixed this time lol. Sorry!

**Review by jeremypw — APPROVED** [review]
Works as expected now.  Only difference noticed is that the height of the dropdown is less requiring scrolling to get to the bottom of the list (for English).  If this is not intended then it can be fixed later.

**Pull request merged**
